language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true

install: travis_retry composer install --no-interaction --prefer-source

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

script: vendor/bin/phpunit --verbose
